host: ip # Server IP
port: 25565 # Server Port
botnick: AuroraBot # Bot NickName
lang: ru # Language. Default language: ru

msg_hidename: false
botprefix: $
autoconsole: false
testmode: false
minwithdraw: 10000
mindeposit: 10000
minbet: 10000
minwithdrawconfirm: 10000
killswitch: false
disablewithdraw: false
casinocooldown: 5000
bjcooldown: 5000
enable_isnearby: false
discord:
  roleid: 'Your Role ID'
ai:
  model: 'Your Model'
  content: 'Your Content'
gui:
  slot: 0
  cmd:
    enable: false
    cmd: games
  hotbar_slot: 0
bannedRunCommands:
  - /sphere
  - /cyl
  - /hcyl
  - /walls
  - /set
  - /faces
  - /overlay
  - /hsphere
  - /pyramid
  - /hpyramid
  - /outline
  - /replacenear
  - /replace
  - /removenear
  - /frb
  - /snow
  - hub
discordBlockedCommands:
  - pay
  - balance
  - feedback
  - code
  - bcode
  - shop
  - casino
  - bj
alwaysAllowed:
  - help
  - info
  - feedback
  - balance
  - pay
  - shop
  - code
  - casino
  - bj
