host: ip # Server IP
port: 25565 # Server Port
botnick: AuroraBot # Bot NickName
lang: ru # Language. Default language: ru
mcversion: "1.21.4" # Minecraft version
msg_hidename: false
botprefix: $
autoconsole: false
testmode: false
minwithdraw: 10000
mindeposit: 10000
minbet: 10000
minwithdrawconfirm: 10000
killswitch: false
disablewithdraw: false
casinocooldown: 5000
bjcooldown: 5000
enable_isnearby: false
enable_chatgame: true
chatgame_interval: 90000
discord:
  roleid: 'Your Role ID'
ai:
  api: "https://openrouter.ai/api/v1/chat/completions"
  model: 'Your Model'
  content: 'Your Content'
  text: "бот,"
  cooldown: 10000
gui:
  slot: 0
  cmd:
    enable: false
    cmd: games
  hotbar_slot: 0
  title: "Menu Title"
chat:
  arrowSymbol: "⇨" # NickName ⇨ Message
  chatFilters:
    includes:
      - "[ʟ]"
      - "[ɢ]"
      - "-> я]"
      - "временно забанил IP-адрес"
    startsWith:
      - "[я ->"
      - "[SS]"
      - ">"
      - "〄 Объявление:"
      - "『КОНСОЛЬ』"
  chatRegex1:
    pattern: "^(❤ )?\\[(ɢ|ʟ)\\]"
    flags: "i"
  chatRegex2:
    pattern: "^❤?\\s?\\[(ɢ|ʟ)\\]\\s?"
    flags: "i"
  moneyRegex:
    pattern: "\\$([\\d]{1,3}(?:,\\d{3})*|\\d+)"
    flags: ""
  coinConvertRegex:
    pattern: "^\\$([\\d]{1,3}(?:,\\d{3})*) получено от игрока (.+?)\\."
    flags: "i"
  realnameRegex: "^~(.+?) is (\\w+)"
  yourbalance: "Ваш баланс:"
  autoconsole_trigger: "Добро пожаловать!"
  unknown_player: ">  Игрок не найден."
bannedRunCommands:
  - /sphere
  - /cyl
  - /hcyl
  - /walls
  - /set
  - /faces
  - /overlay
  - /hsphere
  - /pyramid
  - /hpyramid
  - /outline
  - /replacenear
  - /replace
  - /removenear
  - /frb
  - /snow
  - hub
discordBlockedCommands:
  - pay
  - balance
  - feedback
  - code
  - bcode
  - shop
  - casino
  - bj
alwaysAllowed:
  - help
  - info
  - feedback
  - balance
  - pay
  - shop
  - code
  - casino
  - bj
